# This is a basic workflow to automatically build a Svelte app and deploy it to GitHub Pages

name: Deploy to GitHub Pages
permissions: write-all

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install and Build
        run: |
          cd Narrative-Frontend
          npm install
          npm run build
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: Narrative-Frontend/dist
